######################################## DTU ########################################
Train:
  python runner.py gpu=0 testlist=scan106 outdir=exps_mvs exps_folder=exps_vsdf

Chamfer Distance:
  python evals/eval_dtu.py --datadir exps_mvs --scan 106 --data_dir_root data_s_volsdf

Render:
  python eval_vsdf.py --conf dtu --eval_rendering --data_dir_root data_s_volsdf --expname ours --exps_folder exps_vsdf --evals_folder exps_result --scan_ids 106 --gpu 0
  python eval_vsdf.py --conf dtu --eval_mesh --data_dir_root data_s_volsdf --expname ours --exps_folder exps_vsdf --evals_folder exps_result --scan_ids 106 --gpu 0

PSNR/SSIM/LPIPS:
  python eval_vsdf.py --conf dtu --data_dir_root data_s_volsdf --eval_rendering --expname ours --exps_folder exps_vsdf --evals_folder exps_result --result_from default --scan_ids 106 --gpu 0
  
